### ISSUE TITLE
About logined user's reconnecting.

### ISSUE THREAD

**Issue by Kambaa** [microsoftgraph/php-connect-rest-sample#35]
Hello, 
From what i understand, this code is just connects and checks the token and extract connected user's information to session. What if a connected user is revisits this page, how to validate the session-saved token from microsoft? Could you please add this funcionality to the oauth.php page please. 
Thanks, 
Kambaa

**Comment by jamescro** [comment]
Have you taken a look at these Azure AD samples?

https://github.com/Azure-Samples?utf8=%E2%9C%93&q=php&type=&language=

This sample is more about using the Microsoft Graph REST API. The authentication is simple by design. Azure has a rich collection of samples that demonstrate how to handle more advanced auth scenarios.
